<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.watchtogether</groupId>
        <artifactId>WatchTogetherBackend</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>wt-service</artifactId>
    <packaging>jar</packaging>

    <name>wt-service</name>

    <dependencies>
        <!-- DAO -->
        <dependency>
            <groupId>com.watchtogether</groupId>
            <artifactId>wt-dao</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- 排除 Spring Boot 默认的 Logback 依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- Log4j 2 依赖 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-log4j2</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>